In [1]:
import numpy as np
from random import randint
matrix1 = np.empty((12,12), int)
matrix2 = np.empty((12,12), int)

for i in range(0, 12):
    for j in range(0,12):
        matrix1[i][j] = randint(0,100)
        matrix2[i][j] = randint(0,100)
print(matrix1)

optional_row = matrix1[1]
optional_col = matrix1[:, 4]

print(optional_row)
print(optional_col)

print(matrix1[matrix1 > 5])

[[ 39  61  17  31  20  70  86  18  45  21   6  81]
 [ 22  15  51  43   6   6  88  81  30  66  58  20]
 [ 73  35  34  48  15  77  48  36  31  49  63  45]
 [ 33  61  52  60  63  42  54  96  30   1  20  54]
 [ 99  27  73  96  69  52  55  60  43  82  63  40]
 [ 29  30  17  40  41  67  44  82  64  83   0  42]
 [ 46  94  81   5  25   8  98  40  45  62  90  51]
 [100  94  15  85  32  29  87  57  76  15  20  93]
 [  0  35   1  44  39  43 100  33  31  41  84  13]
 [  6   0  76  72  25  38   7  41  78  17   0  81]
 [ 67  13  51  39  86  76  76  26  97  24  66  90]
 [ 74  47  15  27  76  83  90  92   3  87  95  11]]
[22 15 51 43  6  6 88 81 30 66 58 20]
[20  6 15 63 69 41 25 32 39 25 86 76]
[ 39  61  17  31  20  70  86  18  45  21   6  81  22  15  51  43   6   6
  88  81  30  66  58  20  73  35  34  48  15  77  48  36  31  49  63  45
  33  61  52  60  63  42  54  96  30  20  54  99  27  73  96  69  52  55
  60  43  82  63  40  29  30  17  40  41  67  44  82  64  83  42  46  94
  81  25   8  98  4